name: End-to-end tests 🧪
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - dev
      - 'features\/\d+\\.*'
      - 'features/[1-9].+/.*'
      - 'features/[0-9]-[0-9]-[0-9]-X-BRANCH'
      
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2